version: '3.8'

networks:
  fl-network: # 사용자 정의 네트워크
    driver: bridge

services:
  fl-api:
    image: minseok2000/cozy-api  # Docker Hub에서 이미지를 사용
    container_name: fl-api
    ports:
      - "8080:8080"

    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - FL_CHAT_DB_URL=${FL_CHAT_DB_URL}
      - FL_CHAT_DB_USER_NAME=${FL_CHAT_DB_USER_NAME}
      - FL_DB_URL=${FL_RDS_DB_URL}
      - FL_DB_USER_NAME=${FL_RDS_USER_NAME}
      - FL_DB_PASSWROD=${FL_RDS_PASSWORD}
      - FL_MAP_API_KEY=${FL_MAP_API_KEY}
      - ANDROID_OAUTH_CLIENT_KEY=${ANDROID_OAUTH_CLIENT_KEY}
      - IOS_OAUTH_CLIENT_KEY=${IOS_OAUTH_CLIENT_KEY}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - FL_DOMAIN_BASE=http://host.docker.internal:8080 # 안드로이드 에뮬레이터 호환
      - FL_CHAT_DIRECT_MESSAGE=/dm
      - FL_CHAT_PUBLISH=/pub
      - FL_CHAT_SUBSCRIBE=/sub
    depends_on:
      - mysql
      - redis
    networks:
      - fl-network

  fl-chatting:
    image:  minseok2000/cozy-chatting  # Docker Hub에서 이미지를 사용
    container_name: fl-chatting
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - FL_CHAT_DOMAIN_BASE_URL=${FL_CHAT_DOMAIN_BASE_URL}
      - FL_DB_URL=${FL_RDS_DB_URL}
      - FL_CHAT_DB_URL=${FL_CHAT_DB_URL}
      - FL_CHAT_DB_USER_NAME=${FL_CHAT_DB_USER_NAME}
      - FL_DB_USER_NAME=${FL_RDS_USER_NAME}
      - FL_DB_PASSWROD=${FL_RDS_PASSWORD}
      - FL_MAP_API_KEY=${FL_MAP_API_KEY}
      - ANDROID_OAUTH_CLIENT_KEY=${ANDROID_OAUTH_CLIENT_KEY}
      - IOS_OAUTH_CLIENT_KEY=${IOS_OAUTH_CLIENT_KEY}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - FL_DOMAIN_BASE=http://host.docker.internal:8082 # 안드로이드 에뮬레이터 호환
      - FL_CHAT_DIRECT_MESSAGE=/dm
      - FL_CHAT_PUBLISH=/pub
      - FL_CHAT_SUBSCRIBE=/sub
    depends_on:
      - mysql
      - redis
    networks:
      - fl-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cozyshare_database
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - fl-network

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - fl-network

volumes:
  mysql-data:
    driver: local
