version: '3.8'

services:
  fl-api:
    image: minseok2000/cozy-api
    container_name: fl-api
    expose:
      - "8080"
    ports:
      - "8080:8080"
    env_file:
      - /home/ubuntu/.env

  fl-chatting:
    image: minseok2000/cozy-chatting
    container_name: fl-chatting
    expose:
      - "8082"
    ports:
      - "8082:8082"
    env_file:
      - /home/ubuntu/.env
