# Spring Datasource Configuration
spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comumu?serverTimezone=Asia/Seoul
    username: root
    password: dhsdk1977!
  logging:
    level:
      me.selvernine: DEBUG

  redis:
    host : localhost
    port : 6380

  # JPA Configuration
