spring:
  sql:

    init:
      mode: always
      #continue-on-error: true # 서버 시작시 sql문을 실행할 때 오류 무시하고 계속 진행
      data-locations: classpath:yaml/data.sql
  profiles:
    active: core
  config:
    import:
      - 'classpath:/yaml/application-core-dev.yml'
      - 'classpath:/yaml/application-core-log.yml'
      - 'classpath:/yaml/application-core-local.yml'
jwt:
  secretKey: Z2ZkZmdkZmxrZ2pkbGZrZ2pzYXNkamtoYXNrZGphaHNka2fahgvfahvduyasdffjkhsgdfjkhasgfjkphaGRhc2Rhc2Rhc2Rhc2Rhc2ZhZmdzZAo

  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh

domain:
  chat: http://localhost:8082/api