spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  logging:
    level:
      root: error
      com.api.exception: error
      me.selvernine: ERROR
      com.google.firebase: ERROR
      com.google.api: ERROR
      org.hibernate: error
  data:
    mongodb:
      uri: ${FL_CHAT_DB_URL}
      database: ${FL_CHAT_DB_USER_NAME}
  datasource:
    initialization-mode: never
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${FL_DB_URL}
    username: ${FL_DB_USER_NAME}
    password: ${FL_DB_PASSWROD}
  redis:
    host: ${REDIS_HOST}
    port: 6379


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER_NAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
map:
  api-url: https://maps.googleapis.com/maps/api/geocode/json
  api-key: ${FL_MAP_API_KEY}

aws:
  access:
    key:
      id: ${AWS_ACCESS_KEY_ID}
  secret:
    access:
      key: ${AWS_SECRET_KEY}
  region : ap-southeast-2
  s3:
    bucket:
      name: cozyshare-s3-bucket

admin:
  token: ${ADMIN_TOKEN}

apple:
  key-url: https://appleid.apple.com/auth/keys

oauth:
  android-client-id: ${ANDROID_OAUTH_CLIENT_KEY}
  ios-client-id: ${IOS_OAUTH_CLIENT_KEY}

paypal:
  client-id: ${PAYPAL_CLIENT_ID}
  client-secret: ${PAYPAL_CLIENT_SECRET}
  mode : live

jwt:
  secretKey: ${JWT_KEY}
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Authorization-refresh

thread:
  pool:
    core-pool-size: 4
    queue-capacity: 50
    max-pool-size: 8