spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  logging:
    level:
      me.selvernine: DEBUG
      com.google.firebase: DEBUG
      com.google.api: DEBUG