#로컬 환경 설정
spring:
  data:
    mongodb:
      uri: mongodb+srv://sin1768:sinminseok12@cluster0.kngkt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: chat
  datasource:
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fl_core?serverTimezone=Asia/Seoul
    username: root
    password: sin981023@
  redis:
    host : localhost
    port : 6380
  sql:
    init:
      data-locations: classpath:yaml/data.sql
      mode: always
      continue-on-error: true # 서버 시작시 sql문을 실행할 때 오류 무시하고 계속 진행

domain:
  chat: http://localhost:8082/api