
map:
  api-url: https://maps.googleapis.com/maps/api/geocode/json
  api-key: ${FL_MAP_API_KEY}

aws:
  access:
    key:
      id: ${AWS_ACCESS_KEY_ID}
  secret:
    access:
      key: ${AWS_SECRET_KEY}
  region : ap-southeast-2
  s3:
    bucket:
      name: cozyshare-s3-bucket
admin:
  token: ${ADMIN_TOKEN}

apple:
  key-url: https://appleid.apple.com/auth/keys

oauth:
  android-client-id: ${ANDROID_OAUTH_CLIENT_KEY}
  ios-client-id: ${IOS_OAUTH_CLIENT_KEY}

paypal:
  client-id: ${PAYPAL_CLIENT_ID}
  client-secret: ${PAYPAL_CLIENT_SECRET}
  mode : live


server:
  port: 8082

domain:
  base: ${FL_CHAT_DOMAIN_BASE_URL}
  chat:
    directMessage: /dm
    publish: /pub
    subscribe: /sub

