spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  logging:
    level:
      root: error
      com.api.exception: error
      me.selvernine: ERROR
      com.google.firebase: ERROR
      com.google.api: ERROR
      org.hibernate: error