# Spring Datasource Configuration
spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comumu?serverTimezone=Asia/Seoul
    username: root
    password: sin981023@
  logging:
    level:
      me.selvernine: DEBUG

  # JPA Configuration
