spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  logging:
    file:
      name: /var/log/myapp/application.log
    level:
      root: error
      com.api.exception: info
      me.selvernine: ERROR
      com.google.firebase: ERROR
      com.google.api: ERROR