#개발 환경 설정
# Spring Datasource Configuration
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: simmim1768@gmail.com
    password: vectgfslbunvlhoz
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7

ㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁ
paypal:
  client-id: AbvvFpoZvfxrYZnnHQqIov974vjtxD6zfjZ5MPMMk0nCDnSPhZlJVCpnJICyEEeUWfTDrfayKpIy1lIa
  client-secret: EEokBvdWXAfprqEy8QZXk8B0dKAiOAVcS0HOugWFmLgqRhuEna4aSuzAFWX_6DrIAr-V6dubtEJ5AwUf
  mode : sandbox

jwt:
  secretKey: Z2ZkZmdkZmxrZ2pkbGZrZ2pzYXNkamtoYXNrZGphaHNka2fahgvfahvduyasdffjkhsgdfjkhasgfjkphaGRhc2Rhc2Rhc2Rhc2Rhc2ZhZmdzZAo

  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh

  # JPA Configuration