# Spring Datasource Configuration
spring:

  datasource:
    initialization-mode : always
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hnj?serverTimezone=Asia/Seoul
    username: root

    password: dhsdk1977!

  logging:
    level:
      me.selvernine: DEBUG

  redis:
    host : localhost
    port : 6380

  # JPA Configuration
