spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    sql:
      init:
        mode: always
        #continue-on-error: true # 서버 시작시 sql문을 실행할 때 오류 무시하고 계속 진행
        data-locations: classpath:sql/data.sql