server:
  port: 8081

spring:
  profiles:
    include: shared

domain:
  api: http://localhost:8080/v1/api
  user: http://localhost:8080/v1/api/users/user-info
  home: http://localhost:8080/v1/api/homes
  dm-room:
    list: http://localhost:8080/v1/api/dm/dm-rooms