name: Deploy to EC2

on:
  push:
    branches:
      - fl-master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create .env file from GitHub secret
        run: |
          echo "$ENV_VARS" > .env

      - name: Upload .env and Docker Compose to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          port: 22
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: |
            ./docker-compose.yml
            ./.env
          target: /home/ubuntu/

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          port: 22
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            export PATH=$PATH:/usr/local/bin
            
            # Docker 로그인
            sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            
            # fl-chatting 컨테이너 중지 및 제거
            sudo docker ps -q --filter "name=cozy-chatting" | grep -q . && sudo docker stop cozy-chatting && sudo docker rm -f cozy-chatting || true
            sudo docker stop cozy-api
            sudo docker rm -f cozy-api
            # fl-api 컨테이너 중지 및 제거
            sudo docker ps -q --filter "name=cozy-api" | grep -q . && sudo docker stop cozy-api && sudo docker rm -f cozy-api || true
            sudo docker stop cozy-chatting
            sudo docker rm -f cozy-chatting
            
            # 최신 fl-chatting 이미지 다운로드 및 실행
            sudo docker pull minseok2000/cozy-chatting:latest
            sudo docker run -d \
              --name cozy-chatting \
              --platform linux/amd64 \
              -p 8082:8082 \
              --env-file /home/ubuntu/.env \
              minseok2000/cozy-chatting:latest

            # 최신 fl-api 이미지 다운로드 및 실행
            sudo docker pull minseok2000/cozy-api:latest
            sudo docker run -d \
              --name cozy-api \
              --platform linux/amd64 \
              -p 8080:8080 \
              --env-file /home/ubuntu/.env \
              minseok2000/cozy-api:latest
