name: Deploy to EC2

on:
  push:
    branches:
      - fl-master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker 빌드 설정
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 4. .env 파일 생성
      - name: Create .env file from GitHub secret
        run: |
          echo "FL_DB_URL=${{ secrets.FL_RDS_DB_URL }}" >> .env
          echo "FL_DB_USER_NAME=${{ secrets.FL_DB_USER_NAME }}" >> .env
          echo "FL_DB_PASSWROD=${{ secrets.FL_DB_PASSWROD }}" >> .env
          echo "FL_CHAT_DB_USER_NAME=${{ secrets.FL_CHAT_DB_USER_NAME }}" >> .env
          echo "FL_CHAT_DOMAIN_BASE_URL=${{ secrets.FL_CHAT_DOMAIN_BASE_URL }}" >> .env
          echo "FL_CHAT_DB_URL=${{ secrets.FL_CHAT_DB_URL }}" >> .env
          echo "FL_MAP_API_KEY=${{ secrets.FL_MAP_API_KEY }}" >> .env
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .env
          echo "ANDROID_OAUTH_CLIENT_KEY=${{ secrets.ANDROID_OAUTH_CLIENT_KEY }}" >> .env
          echo "IOS_OAUTH_CLIENT_KEY=${{ secrets.IOS_OAUTH_CLIENT_KEY }}" >> .env
          echo "PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}" >> .env
          echo "PAYPAL_CLIENT_SECRET=${{ secrets.PAYPAL_CLIENT_SECRET }}" >> .env
          echo "JWT_KEY=${{ secrets.JWT_KEY }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "FL_DOMAIN_BASE=${{ secrets.FL_DOMAIN_BASE }}" >> .env
          echo "FL_CHAT_DIRECT_MESSAGE=${{ secrets.FL_CHAT_DIRECT_MESSAGE }}" >> .env
          echo "FL_CHAT_PUBLISH=${{ secrets.FL_CHAT_PUBLISH }}" >> .env
          echo "FL_CHAT_SUBSCRIBE=${{ secrets.FL_CHAT_SUBSCRIBE }}" >> .env
          echo "ADMIN_TOKEN=${{ secrets.ADMIN_TOKEN }}" >> .env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
          echo "MAIL_USER_NAME=${{ secrets.MAIL_USER_NAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env

      - name: Upload .env to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          port: 22
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: ./.env
          target: /home/ubuntu/
          debug: true
          protocol: tcp
          timeout: 30s
          command_timeout: 10m
          tar_exec: tar
          proxy_port: 22
          proxy_timeout: 30s

      - name: Upload docker-compose.yml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          port: 22
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: ./docker-compose.yml
          target: /home/ubuntu/
          debug: true
          protocol: tcp
          timeout: 30s
          command_timeout: 10m
          tar_exec: tar
          proxy_port: 22
          proxy_timeout: 30s

      - name: SSH to EC2 and deploy using docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          port: 22
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose up -d
