name: Deploy to EC2

on:
  push:
    branches:
      - fl-master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker 빌드 설정
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 4. .env 파일 생성
      - name: Create .env file from GitHub secret
        run: |
          echo "FL_RDS_DB_URL=${{ secrets.FL_RDS_DB_URL }}" > .env
          echo "FL_RDS_USER_NAME=${{ secrets.FL_RDS_USER_NAME }}" >> .env
          echo "FL_RDS_PASSWORD=${{ secrets.FL_RDS_PASSWORD }}" >> .env
          echo "FL_CHAT_DB_USER_NAME=${{ secrets.FL_CHAT_DB_USER_NAME }}" >> .env
          echo "FL_CHAT_DOMAIN_BASE_URL=${{ secrets.FL_CHAT_DOMAIN_BASE_URL }}" >> .env
          echo "FL_CHAT_DB_URL=${{ secrets.FL_CHAT_DB_URL }}" >> .env
          echo "FL_MAP_API_KEY=${{ secrets.FL_MAP_API_KEY }}" >> .env
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .env
          echo "ANDROID_OAUTH_CLIENT_KEY=${{ secrets.ANDROID_OAUTH_CLIENT_KEY }}" >> .env
          echo "IOS_OAUTH_CLIENT_KEY=${{ secrets.IOS_OAUTH_CLIENT_KEY }}" >> .env
          echo "PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}" >> .env
          echo "PAYPAL_CLIENT_SECRET=${{ secrets.PAYPAL_CLIENT_SECRET }}" >> .env
          echo "JWT_KEY=${{ secrets.JWT_KEY }}" >> .env
          cat .env
      - name: Check if .env and docker-compose.yml exist
        run: |
          ls -la .env
          cat .env  # .env 파일 내용 확인
          ls -la docker-compose.yml
      - name: Check files in workspace
        run: |
          ls -la .
          ls -la ./docker-compose.yml
          ls -la ./.env

      - name: Upload .env and Docker Compose to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          port: 22
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: |
            docker-compose.yml
            ./.env
          target:
          debug: true

      # 6. EC2에서 파일 확인 (디버깅용)
      - name: Check files existence
        run: |
          ls -la ./docker-compose.yml
          ls -la ./.env

      # 7. EC2에 SSH로 접속하여 Docker 컨테이너 배포
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          port: 22
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            export PATH=$PATH:/usr/local/bin
            
            # Docker 로그인
            sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            
            # 기존 컨테이너들 중지 및 제거
            sudo docker ps -q --filter "name=cozy-chatting" | grep -q . && sudo docker stop cozy-chatting && sudo docker rm -f cozy-chatting || true
            sudo docker ps -q --filter "name=cozy-api" | grep -q . && sudo docker stop cozy-api && sudo docker rm -f cozy-api || true
            
            # 최신 fl-chatting 이미지 다운로드 및 실행
            sudo docker pull minseok2000/cozy-chatting:latest
            sudo docker run -d \
              --name cozy-chatting \
              --platform linux/amd64 \
              -p 8082:8082 \
              --env-file /home/ubuntu/.env \
              minseok2000/cozy-chatting:latest

            # 최신 fl-api 이미지 다운로드 및 실행
            sudo docker pull minseok2000/cozy-api:latest
            sudo docker run -d \
              --name cozy-api \
              --platform linux/amd64 \
              -p 8080:8080 \
              --env-file /home/ubuntu/.env \
              minseok2000/cozy-api:latest
