name: Deploy to EC2

on:
  push:
    branches:
      - fl-master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./ ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/project

      - name: SSH to EC2 and deploy
        env:
          FL_CHAT_DB_URL: ${{ secrets.FL_CHAT_DB_URL }}
          FL_CHAT_DB_USER_NAME: ${{ secrets.FL_CHAT_DB_USER_NAME }}
          FL_RDS_DB_URL: ${{ secrets.FL_RDS_DB_URL }}
          FL_RDS_USER_NAME: ${{ secrets.FL_RDS_USER_NAME }}
          FL_RDS_PASSWORD: ${{ secrets.FL_RDS_PASSWORD }}
          FL_MAP_API_KEY: ${{ secrets.FL_MAP_API_KEY }}
          ANDROID_OAUTH_CLIENT_KEY: ${{ secrets.ANDROID_OAUTH_CLIENT_KEY }}
          IOS_OAUTH_CLIENT_KEY: ${{ secrets.IOS_OAUTH_CLIENT_KEY }}
          PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
          PAYPAL_CLIENT_SECRET: ${{ secrets.PAYPAL_CLIENT_SECRET }}
          FL_CHAT_DOMAIN_BASE_URL: ${{ secrets.FL_CHAT_DOMAIN_BASE_URL }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ubuntu/project
            sudo docker-compose down
            sudo docker-compose up -d --build
          EOF
